# Generated by Django 2.2 on 2021-03-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_model_info',
            fields=[
                ('price_model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='无', max_length=100, verbose_name='名称')),
                ('proportion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='加价比列')),
                ('level', models.IntegerField(choices=[(0, '默认'), (9, '最高级'), (2, '自定义'), (1, '节假日')], default=0, verbose_name='优先级')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '加价类型表',
                'verbose_name_plural': '加价类型表',
                'db_table': 'price_model_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(default='无', max_length=100, verbose_name='房型')),
                ('hotelid', models.CharField(max_length=50, null=True, verbose_name='酒店ID')),
                ('channel', models.CharField(max_length=100, verbose_name='渠道')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='报价')),
                ('custom_proce', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='强制自定义售价')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price_model', models.ManyToManyField(to='hotel_order.Price_model_info', verbose_name='加价类型')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_info',
                'managed': True,
            },
        ),
    ]
