# Generated by Django 2.2 on 2021-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='custom_proce',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='price_model',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='room_type',
        ),
        migrations.AddField(
            model_name='order_info',
            name='checkInDate',
            field=models.CharField(default='', max_length=20, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='checkOutDate',
            field=models.CharField(default='', max_length=20, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='hotelRemark',
            field=models.TextField(default='', verbose_name='酒店备注'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='prices',
            field=models.CharField(default='', max_length=100, verbose_name='酒店报价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_info',
            name='prices_up',
            field=models.CharField(default='', max_length=100, verbose_name='实际价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_info',
            name='roomGroups',
            field=models.TextField(default='', verbose_name='入住信息'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_info',
            name='hotelid',
            field=models.CharField(default='', max_length=50, verbose_name='酒店ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(0, '默认'), (2, '自定义'), (9, '最高级'), (1, '节假日')], default=0, verbose_name='优先级'),
        ),
    ]
