# Generated by Django 2.2 on 2021-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_order', '0002_auto_20210323_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(2, '自定义'), (9, '最高级'), (0, '默认'), (1, '节假日')], default=0, verbose_name='优先级'),
        ),
    ]
