# Generated by Django 2.2 on 2021-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_order', '0004_auto_20210324_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_info',
            old_name='statuc',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(1, '节假日'), (0, '默认'), (2, '自定义'), (9, '最高级')], default=0, verbose_name='优先级'),
        ),
    ]
