# Generated by Django 2.2 on 2021-03-03 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City_info',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('countryId', models.IntegerField(default=0, verbose_name='国家编号')),
                ('countryCn', models.CharField(default='未知', max_length=20, verbose_name='国家中文名')),
                ('countryEn', models.CharField(default='未知', max_length=20, verbose_name='国家英文名')),
                ('stateId', models.IntegerField(default=0, verbose_name='省份编号')),
                ('stateCn', models.CharField(default='未知', max_length=20, verbose_name='省份中文名')),
                ('stateEn', models.CharField(default='未知', max_length=20, verbose_name='省份英文名')),
                ('cityId', models.IntegerField(default=0, verbose_name='城市编号')),
                ('cityCn', models.CharField(default='未知', max_length=20, verbose_name='城市中文名')),
                ('cityEn', models.CharField(default='未知', max_length=20, verbose_name='城市英文名')),
                ('is_effective', models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '城市信息表',
                'verbose_name_plural': '城市信息表',
                'db_table': 'city_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel_info',
            fields=[
                ('hotel_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('hotelId', models.IntegerField(verbose_name='酒店编号')),
                ('countryId', models.IntegerField(verbose_name='国家编号')),
                ('stateId', models.IntegerField(verbose_name='省份编号')),
                ('cityId', models.IntegerField(verbose_name='城市编号')),
                ('star', models.IntegerField(verbose_name='酒店星级')),
                ('hotelNameCn', models.CharField(default='无', max_length=100, verbose_name='酒店中文名')),
                ('hotelNameEn', models.CharField(default='无', max_length=100, verbose_name='酒店英文名')),
                ('addressCn', models.CharField(default='无', max_length=100, verbose_name='中文地址')),
                ('addressEn', models.CharField(default='无', max_length=100, verbose_name='英文地址')),
                ('phone', models.CharField(default='无', max_length=100, verbose_name='酒店总机')),
                ('longitude', models.CharField(default='无', max_length=20, verbose_name='经度')),
                ('latitude', models.CharField(default='无', max_length=20, verbose_name='纬度')),
                ('instantConfirmation', models.IntegerField(verbose_name='是否即时确认')),
                ('sellType', models.IntegerField(verbose_name='是否热销酒店')),
                ('updateTime', models.CharField(default='无', max_length=100, verbose_name='酒店方的修改时间')),
                ('is_effective', models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用')),
                ('detail', models.TextField(verbose_name='备注')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ciyt_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='hotel_admin.City_info')),
                ('sys_create_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建人')),
            ],
            options={
                'verbose_name': '酒店信息表',
                'verbose_name_plural': '酒店信息表',
                'db_table': 'hotel_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Price_model_info',
            fields=[
                ('price_model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='无', max_length=100, verbose_name='名称')),
                ('proportion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='加价比列')),
                ('level', models.IntegerField(choices=[(9, '最高级'), (2, '自定义'), (0, '默认'), (1, '节假日')], default=0,
                                              verbose_name='优先级')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sys_create_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建人')),
            ],
            options={
                'verbose_name': '加价类型表',
                'verbose_name_plural': '加价类型表',
                'db_table': 'price_model_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(default='无', max_length=100, verbose_name='房型')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='报价')),
                ('custom_proce',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='强制自定义售价')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_admin.Hotel_info',
                                   verbose_name='酒店')),
                ('price_model', models.ManyToManyField(to='hotel_admin.Price_model_info', verbose_name='加价类型')),
                ('sys_create_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建人')),
            ],
            options={
                'verbose_name': '房间信息表',
                'verbose_name_plural': '房间信息表',
                'db_table': 'room_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(default='无', max_length=100, verbose_name='房型')),
                ('channel', models.CharField(max_length=100, verbose_name='渠道')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='报价')),
                ('custom_proce',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='强制自定义售价')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_admin.Hotel_info',
                                   verbose_name='酒店')),
                ('price_model', models.ManyToManyField(to='hotel_admin.Price_model_info', verbose_name='加价类型')),
                ('sys_create_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_info',
                'managed': True,
            },
        ),
    ]
