# Generated by Django 2.2 on 2021-03-13 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate_info',
            new_name='Rate_type_info',
        ),
        migrations.RenameModel(
            old_name='Room_info',
            new_name='Room_type_info',
        ),
        migrations.AlterModelOptions(
            name='rate_type_info',
            options={'managed': True, 'verbose_name': '价格类型', 'verbose_name_plural': '价格类型'},
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(1, '节假日'), (9, '最高级'), (0, '默认'), (2, '自定义')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageLogo',
            field=models.IntegerField(choices=[(1, '无水印logo'), (0, '有水印logo'), (-1, '未知')], default=-1, verbose_name='是否带水印'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(3, '640 * 960'), (0, '未分类'), (1, '350 * 350'), (2, '550 * 412')], default=0, verbose_name='图片规格'),
        ),
        migrations.AlterModelTable(
            name='rate_type_info',
            table='rate_type_info',
        ),
        migrations.AlterModelTable(
            name='room_type_info',
            table='Room_type_info',
        ),
    ]
