# Generated by Django 2.2 on 2021-03-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='is_effective',
            field=models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='is_effective',
            field=models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='star',
            field=models.CharField(default=0, max_length=20, verbose_name='酒店星级'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(9, '最高级'), (2, '自定义'), (0, '默认'), (1, '节假日')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageLogo',
            field=models.IntegerField(choices=[(0, '有水印logo'), (-1, '未知'), (1, '无水印logo')], default=-1, verbose_name='是否带水印'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(0, '未分类'), (1, '350 * 350'), (3, '640 * 960'), (2, '550 * 412')], default=0, verbose_name='图片规格'),
        ),
    ]
