# Generated by Django 2.2 on 2021-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hotel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='cityEn',
            field=models.CharField(default='未知', max_length=200, verbose_name='城市英文名'),
        ),
        migrations.AlterField(
            model_name='city_info',
            name='countryEn',
            field=models.CharField(default='未知', max_length=200, verbose_name='国家英文名'),
        ),
        migrations.AlterField(
            model_name='city_info',
            name='stateEn',
            field=models.CharField(default='未知', max_length=200, verbose_name='省份英文名'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(1, '节假日'), (0, '默认'), (2, '自定义'), (9, '最高级')], default=0,
                                      verbose_name='优先级'),
        ),
    ]
