# Generated by Django 2.2 on 2021-03-13 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_admin', '0002_auto_20210313_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='is_effective',
            field=models.IntegerField(choices=[(0, '不启用'), (1, '启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='is_effective',
            field=models.IntegerField(choices=[(0, '不启用'), (1, '启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(0, '默认'), (9, '最高级'), (2, '自定义'), (1, '节假日')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(3, '640 * 960'), (2, '550 * 412'), (1, '350 * 350'), (0, '未分类')], default=0, verbose_name='图片规格'),
        ),
        migrations.CreateModel(
            name='RatePlan_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(default='未知', max_length=50, verbose_name='渠道')),
                ('keyId', models.CharField(default='', max_length=50, verbose_name='产品编号')),
                ('supplierId', models.IntegerField(default=0, verbose_name='供应商ID')),
                ('keyName', models.CharField(default='', max_length=50, verbose_name='房型名称')),
                ('bedName', models.CharField(default='', max_length=50, verbose_name='床型名称')),
                ('maxOccupancy', models.IntegerField(default=0, verbose_name='最大入住人数')),
                ('currency', models.CharField(default='', max_length=50, verbose_name='币种')),
                ('rateTypeId', models.CharField(default='', max_length=50, verbose_name='价格类型编号')),
                ('paymentType', models.IntegerField(default=0, verbose_name='付款类型')),
                ('breakfast', models.IntegerField(default=0, verbose_name='早餐')),
                ('ifInvoice', models.IntegerField(default=0, verbose_name='是否开票')),
                ('bookingRuleId', models.CharField(default='', max_length=50, verbose_name='预订条款编号')),
                ('refundRuleId', models.CharField(default='', max_length=50, verbose_name='取消条款编号')),
                ('market', models.CharField(default='', max_length=50, verbose_name='适用市场')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateplans', to='hotel_admin.Hotel_info', verbose_name='酒店')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'db_table': 'rateplan_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel_RefundRule_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(default='未知', max_length=50, verbose_name='渠道')),
                ('refundRuleId', models.CharField(max_length=50, verbose_name='取消条款编号')),
                ('refundRuleType', models.IntegerField(default=1, verbose_name='取消条款规则')),
                ('refundRuleHours', models.IntegerField(default=30, verbose_name='入住前n小时')),
                ('deductType', models.IntegerField(default=1, verbose_name='取消客人罚金')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refundrules', to='hotel_admin.Hotel_info', verbose_name='酒店')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '取消条款信息',
                'verbose_name_plural': '取消条款信息',
                'db_table': 'hotel_refundrule_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel_Promotion_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(default='未知', max_length=50, verbose_name='渠道')),
                ('startDate', models.CharField(default='', max_length=200, verbose_name='礼包开始时间')),
                ('endDate', models.CharField(default='', max_length=200, verbose_name='礼包结束时间')),
                ('description', models.CharField(default='', max_length=200, verbose_name='礼包描述')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('RatePlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='hotel_admin.RatePlan_info', verbose_name='酒店产品')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '礼包信息',
                'verbose_name_plural': '礼包信息',
                'db_table': 'hotel_promotion_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel_NightlyRate_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(default='未知', max_length=50, verbose_name='渠道')),
                ('formulaTypen', models.CharField(default='', max_length=50, verbose_name='配额类型')),
                ('date', models.CharField(default='', max_length=20, verbose_name='日期')),
                ('cose', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='价格')),
                ('status', models.IntegerField(default=0, verbose_name='房态')),
                ('currentAlloment', models.IntegerField(default=0, verbose_name='库存')),
                ('breakfast', models.IntegerField(default=0, verbose_name='早餐')),
                ('bookingRuleId', models.CharField(default='', max_length=20, verbose_name='预订条款编号')),
                ('refundRuleId', models.CharField(default='', max_length=20, verbose_name='取消条款编号')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Rateplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nightlyRates', to='hotel_admin.RatePlan_info', verbose_name='酒店产品')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_admin.Hotel_info', verbose_name='酒店')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '夜间数据',
                'verbose_name_plural': '夜间数据',
                'db_table': 'hotel_nightlyrate_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel_BookingRule_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(default='未知', max_length=50, verbose_name='渠道')),
                ('bookingRuleId', models.CharField(max_length=100, verbose_name='预订条款编号')),
                ('startDate', models.CharField(max_length=100, verbose_name='开始日期')),
                ('endDate', models.CharField(max_length=100, verbose_name='结束日期')),
                ('minAmount', models.IntegerField(default=1, verbose_name='预订最少数量')),
                ('maxAmount', models.IntegerField(default=7, verbose_name='预订最多数量')),
                ('minDays', models.IntegerField(default=1, verbose_name='最少入住天数')),
                ('maxDays', models.IntegerField(default=30, verbose_name='最多入住天数')),
                ('minAdvHours', models.IntegerField(default=0, verbose_name='最少提前预订时间')),
                ('maxAdvHours', models.IntegerField(default=-1, verbose_name='最大提前预订时间')),
                ('weekSet', models.CharField(max_length=100, verbose_name='有效星期')),
                ('startTime', models.CharField(max_length=100, verbose_name='每日开始销售时间')),
                ('endTime', models.CharField(max_length=100, verbose_name='每日结束销售时间')),
                ('bookingNotices', models.CharField(max_length=2000, verbose_name='预订说明')),
                ('sys_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sys_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingrules', to='hotel_admin.Hotel_info', verbose_name='酒店')),
                ('sys_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '预订条款信息',
                'verbose_name_plural': '预订条款信息',
                'db_table': 'hotel_bookingrule_info',
                'managed': True,
            },
        ),
    ]
