# Generated by Django 2.2 on 2021-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hotel_admin', '0002_auto_20210304_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='cityEn',
            field=models.CharField(default='未知', max_length=500, verbose_name='城市英文名'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(2, '自定义'), (0, '默认'), (1, '节假日'), (9, '最高级')], default=0,
                                      verbose_name='优先级'),
        ),
    ]
