# Generated by Django 2.2 on 2021-03-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0003_auto_20210312_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='is_effective',
            field=models.IntegerField(choices=[(0, '不启用'), (1, '启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='is_effective',
            field=models.IntegerField(choices=[(0, '不启用'), (1, '启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(9, '最高级'), (0, '默认'), (1, '节假日'), (2, '自定义')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageLogo',
            field=models.IntegerField(choices=[(1, '无水印logo'), (0, '有水印logo'), (-1, '未知')], default=-1, verbose_name='是否带水印'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(1, '350 * 350'), (3, '640 * 960'), (0, '未分类'), (2, '550 * 412')], default=0, verbose_name='图片规格'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotel_admin.Hotel_info', verbose_name='酒店'),
        ),
    ]
