# Generated by Django 2.2 on 2021-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0004_auto_20210322_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_info',
            name='is_effective',
            field=models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='is_effective',
            field=models.IntegerField(choices=[(1, '启用'), (0, '不启用')], default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(2, '550 * 412'), (3, '640 * 960'), (1, '350 * 350'), (0, '未分类')], default=0, verbose_name='图片规格'),
        ),
    ]
