# Generated by Django 2.2 on 2021-03-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0004_auto_20210312_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_info',
            name='instantConfirmation',
            field=models.IntegerField(default=0, verbose_name='是否即时确认'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='sellType',
            field=models.IntegerField(default=0, verbose_name='是否热销酒店'),
        ),
        migrations.AlterField(
            model_name='price_model_info',
            name='level',
            field=models.IntegerField(choices=[(9, '最高级'), (0, '默认'), (2, '自定义'), (1, '节假日')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='rate_info',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='hotel_admin.Hotel_info', verbose_name='酒店'),
        ),
        migrations.AlterField(
            model_name='rate_info',
            name='rateTypeId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='价格类型编号'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='hotel_admin.Hotel_info', verbose_name='酒店'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageLogo',
            field=models.IntegerField(choices=[(0, '有水印logo'), (-1, '未知'), (1, '无水印logo')], default=-1, verbose_name='是否带水印'),
        ),
        migrations.AlterField(
            model_name='room_image_info',
            name='imageSize',
            field=models.IntegerField(choices=[(1, '350 * 350'), (3, '640 * 960'), (2, '550 * 412'), (0, '未分类')], default=0, verbose_name='图片规格'),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='roomTypeEn',
            field=models.CharField(default='无', max_length=100, verbose_name='客房英文名称'),
        ),
    ]
